name: Tests

on:
  push:
    branches:
      - main

env:
  TF_IN_AUTOMATION: "true"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        run: terraform fmt -check
      
      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate
